version: 2.1
jobs:
  build:
    docker: 
      - image: node:11.1.0-alpine # the primary container, where your job's commands are run
    steps:
      - checkout 

      - setup_remote_docker:
          docker_layer_caching: true # (3)
          
      # build and push Docker image
      - run: |
      
          TAG=rtapp.$CIRCLE_BUILD_NUM
          docker build -t $TAG .
          docker run --p3001:3000 --name ra $TAG
            
          docker login -u $DOCKER_USER -p $DOCKER_PASS 
          docker push jayapulicherla/jayacodesample:$TAG
          