version: 2.1
orbs:
  docker: circleci/docker@1.0.1
    
jobs:
  build:
    docker: 
      - image: docker:stable-git # the primary container, where your job's commands are run
      #- image: circleci/buildpack-deps:stable-curl
      #- image: cypress/included:3.2.0
    steps:
      - checkout 

      - setup_remote_docker:
          docker_layer_caching: true # (3)
          
      # build and push Docker image
      - run: |
      
          TAG=rtapp.$CIRCLE_BUILD_NUM
          docker build -t $TAG .
          
          #docker run -a stderr ubuntu echo test
          docker run -dit -p 3001:3000 --name ra $TAG 
          apk update && apk add curl curl-dev bash
          docker ps
          docker exec ra curl --retry 10 --retry-connrefused http://localhost:3000
          #docker inspect $TAG
          #docker exec -it $TAG /bin/bash
          #docker exec -it 
          echo $PWD
          #docker run -it -v $PWD:/e2e -w /e2e cypress/included:3.2.0
          docker inspect $TAG
          #echo "nammavar periyavar"
          #docker run -dit --name tecmint-web -p 8080:80 -v /home/user/website/:/usr/local/apache2/htdocs/ httpd:2.4
          #apt-get install curl cypress
          curl -L http://host.docker.internal:3001
          #npx cypress open
          #npx cypress run -- --record --spec "cypress/integration/react_app.js"
                  
          #docker ps
          command: |
             echo "nammavar periyavar"
             curl -L http://localhost:3001
            
          #docker stop ra
          #docker login -u $DOCKER_USER -p $DOCKER_PASS 
          #docker push jayapulicherla/jayacodesample:$TAG
          