version: 2.1
orbs:
  docker: circleci/docker@1.0.1
    
jobs:
  build:
    docker: 
      - image: docker:stable-git # the primary container, where your job's commands are run
      - image: circleci/buildpack-deps:stable-curl
     
    steps:
      - checkout 

      - setup_remote_docker:
          docker_layer_caching: true # (3)
     
      - run: |
      
          TAG=rtapp.$CIRCLE_BUILD_NUM
          docker build -t $TAG .
          docker run -dit -p 3001:3000 --name ra $TAG          
         
          docker cp ./ ra:/e2e
   
          echo  "Run cypress run"
          docker container exec -it ra /app/node_modules/.bin/cypress run
         
          #docker stop ra
          #docker login -u $DOCKER_USER -p $DOCKER_PASS 
          #docker push jayapulicherla/jayacodesample:$TAG
          