version: 2.1
orbs:
  docker: circleci/docker@1.0.1
    
jobs:
  build:
    docker: 
      - image: docker:stable-git # the primary container, where your job's commands are run
      - image: circleci/buildpack-deps:stable-curl
      #- image: cypress/included:3.2.0
    steps:
      - checkout 

      - setup_remote_docker:
          docker_layer_caching: true # (3)
          
      # build and push Docker image
      - run: |
      
          TAG=rtapp.$CIRCLE_BUILD_NUM
          docker build -t $TAG .
          
          docker run -a stderr ubuntu echo test
          #docker run -it -p 127.0.0.1:3001:3000 $TAG
          
          #docker exec -it 
          #docker run -it -v $PWD/cypress/integration:/e2e -w /e2e cypress/included:3.2.0
          echo "nammavar periyavar"
          #apt-get install curl cypress
          #curl http://localhost:3000
          #npx cypress open
          #npx cypress run -- --record --spec "cypress/integration/react_app.js"
                  
          command: |
             echo "nammavar periyavar"
            
          #docker stop ra
          #docker login -u $DOCKER_USER -p $DOCKER_PASS 
          #docker push jayapulicherla/jayacodesample:$TAG
          